before:
  hooks:
    - go mod download
builds:
  -
    id: go_multiarch
    binary: go_multiarch
    tags:
      - osusergo
      - netgo
      - static_build
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
changelog:
  skip: true
