before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
  - binary: go_multiarch
    id: go_multiarch
    goos:
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - 6
      - 7
