before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
  - binary: go_multiarch
    id: go_multiarch
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
